import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  UnifiedWalletButton,
  UnifiedWalletProvider,
} from "@jup-ag/wallet-adapter";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <UnifiedWalletProvider
          wallets={[]}
          config={{
            autoConnect: false,
            env: "mainnet-beta",
            metadata: {
              name: "UnifiedWallet",
              description: "UnifiedWallet",
              url: "https://jup.ag",
              iconUrls: ["https://jup.ag/favicon.ico"],
            },
            walletlistExplanation: {
              href: "https://station.jup.ag/docs/additional-topics/wallet-list",
            },
          }}
        >
          <UnifiedWalletButton />
        </UnifiedWalletProvider>
      </main>
    </>
  );
}
